volumes:
  rglua_database_internals:
    labels: 
      clear: "rglua"
      
services:
  rglua_db:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - rglua_database_internals:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # TODO: WIP enable/disable depending on env var for dev/prod
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8888:8080

  blue_player:
    build:
      context: ../
      dockerfile: ./player/deployment/Dockerfile
      args:
        - PORT=1111
    command: " -p 1111"
    ports:
      - 1111:1111
  red_player:
    build:
      context: ../
      dockerfile: ./player/deployment/Dockerfile
      args:
        - PORT=2222
    command: " -p 2222"
    ports:
      - 2222:2222

  referee:
    build:
      context: ../
      dockerfile: ./referee/deployment/Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - rglua_db
      - blue_player
      - red_player

  matchmaker:
    build:
      context: ../
      dockerfile: ./matchmaker/deployment/Dockerfile
    ports:
      - 4444:4444
    depends_on:
      - rglua_db
      - referee

